---

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zk-data:/var/lib/zookeeper/data
      - ./zk-txn-logs:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-enterprise-kafka:7.7.1
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    env_file:
      - ./env/kafka_common.env
      - ./env/kafka1_custom.env

  kafka2:
    image: confluentinc/cp-enterprise-kafka:7.7.1
    hostname: kafka2
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    env_file:
      - ./env/kafka_common.env
      - ./env/kafka2_custom.env

  kafka3:
    image: confluentinc/cp-enterprise-kafka:7.7.1
    hostname: kafka3
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "29094:29094"
    env_file:
      - ./env/kafka_common.env
      - ./env/kafka3_custom.env

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9092,PLAINTEXT://kafka3:9092
    ports:
      - "8081:8081"

  kafka-admin:
    image: tchiotludo/akhq
    hostname: kafka-admin
    container_name: kafka-admin
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:9092, kafka2:9092, kafka3:9092"
              schema-registry:
                url: "http://schema-registry:8081"
    ports:
      - 8095:8080
    links:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry